fix = false
line-length = 100
indent-width = 4

[lint]
select = [
    "E", # PEP8 errors
    "F", # PyFlakes
    "W", # PEP8 warnings
    "C90", # McCabe complexity
    "I", # Isort errors
    "N", # PEP8 Naming Conventions
    "D", # Pydocstyle - Docstring Conventions
    "UP", # PyUpgrade - Modernizes Python code for version 3.6+
    "YTT", # flake8-2020 - Avoids using sys.version deprecated attributes
    "ANN", # flake8-annotations - Mandatory type annotations
    "ASYNC", # flake8-async - Checks for common async pitfalls
    "S", # flake8-bandit - Security checks
    "FBT003", # flake8-boolean-trap - Disallow boolean positional arguments in function calls
    "B", # flake8-bugbear - Prevent common bugs and design problems
    "A", # flake8-builtins - Checks for python builtins being shadwowed by local variables
    "COM", # flake8-commas - Checks for missing or extra commas in lists and dicts
    "C4", # flake8-comprehensions - Checks for list comprehensions shenanigans
    "DTZ", # flake8-datetimez - Checks for common datetime mistakes
    "T10", # flake8-debugger - Checks for pdb/ipdb imports and set_trace calls
    # "DJ", # flake8-django - Checks for common Django mistakes
    "FA100", # Checks for missing future annotations to allow PEP 585 in python < 3.9
    "ISC", # flake8-implicit-str-concat - Checks for implicit string concatenations
    "ICN", # flake8-import-conventions - Checks for import order and naming conventions CIENTIFICOS
    # LOGGING # - Probalby use loguru
    # "LOG", # flake8-logging - Checks for issues using the standard library logging module
    # "G", # flake8-loggin-format - Checks for logging format string issues - Discuss
    # /LOGGING #
    "INP", # flake8-no-pep420 - Checks for implicit namespace packages
    "PIE", # flake8-pie - Caquilla varia
    "T20", # flake8-print - Checks for print statements
    # "PYI", # flake8-pyi - Lint Stub files !! only for stubs !! - leave, rediscuss if issue
    "PT", # flake8-pytest-style - Checks for pytest style recommendations !! Only if using pytest !!
    "Q", # flake8-quotes - Checks for consistent quotes !! Discuss !!
    "RSE", # flake8-raise - Avoids unnecessary parenthesis in raise statements
    "RET", # flake8-return - Checks function return good practices
    "SLF", # flake8-self - Prevents accessing private attributes outside the class !! Discuss !! IGNORE FOR TESTING
    "SLOT", # flake8-slot - Checks for missing __slots__ in inmutable subclasses to save memory
    "SIM", # flake8-simplify - Checks for simplifications in code !! Discuss individual cases !!
    "TID251", # flake8-tidy-imports - Allows banning of imports from specific modules
    "TID252", # flake8-tidy-imports - Prefer absolute imports over relative imports !! Discuss !!
    "TCH", # flake8-type-checking - Suggests moving imports for type checking in TYPE_CHECKING block !! Discuss individual warnings !!
    # "INT", # flake8-gettext - Checks for common issues in gettext usage !! Discuss !!
    "ARG", # flake8-unused-arguments - Checks for unused arguments in functions
    "PTH", # flake8-use-pathlib - Should we use pathlib instead of os.path?? !! Discuss !!
    "TD", # flake8-todo - Checks TODO comments !! Discuss !!
    "ERA", # flake8-eradicate - Checks for commented out code
    # "PD", # pandas-vet - Checks for common pandas mistakes CIENTIFICOS
    "PGH003", # pygrep-hooks - Mandatory # type: ignore rule speification
    "PGH004", # pygrep-hooks - Mandatory # noqa rule speification
    "PGH005", # pygrep-hooks - Makes sure all mock methods are called instead of accessed
    "PLC", # pylint-conventions - Checks for common conventions !! Discuss individual warnings !!
    "PLE", # pylint-errors - Checks for common errors !! Discuss individual warnings !!
    "PLR", # pylint-refactor - Checks for common refactoring suggestions !! Discuss individual warnings !!
    "PLW", # pylint-warnings - Checks for common warnings !! Discuss individual warnings !!
    # "TRY", # tryceratops - Checks for common try/except antipatterns !! Discuss !!
    "FLY002", # flynt - Suggest using f-strings instead of "".join() !! Discuss !!
    "NPY", # numpy-style - Checks for numpy style conventions CIENTIFICOS
    "FAST", # FastAPI - Checks for FastAPI best practices !! Discuss !!
    "PERF", # Performance - Checks for performance antipatterns
    "FURB", # refurb - Modernize codebase !! Discuss individual warnings !!
    "DOC", # pydoclint - Mandatory docstring format !! Discuss individual warnings !!
    "RUF", # ruff - Ruff specific rules

]

ignore = [
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public class
    "D104", # Missing docstring in public package
    "D106", # Missing docstring in public nested class
    "D107", # Missing docstring in __init__
    "D200", # One-line docstring should fit on one line with quotes !! Discuss !!
    "D203", # 1 blank line required before class docstring
    "D212", # Multi-line docstring summary should start at the second line (conflicts with D211)
    "ANN101", # Missing type annotation for self in method
    "ANN102", # Missing type annotation for cls in classmethod
    "DTZ007", # Naive datetime constructed using datetime.datetime.strptime() without %z
    "ISC003", # Explicitly concatenated string should be implicitly concatenated
    "LOG007", # Use of logging.exception with falsy exc_info
    "PT004", # Add _ to fixtures that do not return a value
    "RET503", # Check for missing explicit return None at the end of a function !! Discuss !!
    "PERF203", # Disallow try/except inside loop !! Discuss !!
    "SIM105", # Use contextlib.suppress({exception}) instead of try-except-pass
    "SIM110", # Use any instead of for loop
    "SIM300", # Prevent yoda conditions
    "TID253", # flake8-tidy-imports - Allows banning module-level imports for specific modules
    "TC008", # Remove quotes from type alias
    "TD002", # Disallow TODO comments without author name
    "FIX", # flake8-fixme - Checks FIXME comments



]

[lint.pydocstyle]
convention = "google"

[lint.flake8-annotations]
allow-star-arg-any = true
suppress-dummy-args = true

[lint.flake8-unused-arguments]
ignore-variadic-names = true

[lint.mccabe]
max-complexity = 5

[lint.pylint]
max-statements = 5


